package POJO;
// Generated 01-mar-2016 10:02:24 by Hibernate Tools 4.3.1



/**
 * Multicine generated by hbm2java
 */
public class Multicine  implements java.io.Serializable {


     private Integer codigoM;
     private String nombre;
     private String ubicacion;

    public Multicine() {
    }

    public Multicine(String nombre, String ubicacion) {
       this.nombre = nombre;
       this.ubicacion = ubicacion;
    }
   
    public Integer getCodigoM() {
        return this.codigoM;
    }
    
    public void setCodigoM(Integer codigoM) {
        this.codigoM = codigoM;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }




}


