package POJO;
// Generated 01-mar-2016 10:02:24 by Hibernate Tools 4.3.1


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.sql.Time;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.Date;

/**
 * Proyeccion generated by hbm2java
 */
public class Proyeccion implements java.io.Serializable {

    private int codigo;
    private Peliculas peliculas;
    private Sala sala;
    private Date horaProyeccioon;

    public Proyeccion() {
    }

    public Proyeccion(Peliculas peliculas, Sala sala, LocalTime horaProyeccioon) {
        this.peliculas = peliculas;
        this.sala = sala;
        this.setHoraProyeccioon(horaProyeccioon);
    }

    public Proyeccion(int codigo, Peliculas peliculas, Sala sala, LocalTime horaProyeccioon) {
        this.codigo = codigo;
        this.peliculas = peliculas;
        this.sala = sala;
       this.setHoraProyeccioon(horaProyeccioon);
    }

    public int getCodigo() {
        return this.codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public Peliculas getPeliculas() {
        return this.peliculas;
    }

    public void setPeliculas(Peliculas peliculas) {
        this.peliculas = peliculas;
    }

    public Sala getSala() {
        return this.sala;
    }

    public void setSala(Sala sala) {
        this.sala = sala;
    }

    public Date getHoraProyeccioon() {
        return this.horaProyeccioon;
    }

    public void setHoraProyeccioon(LocalTime horaProyeccioon) {
        Time tm = Time.valueOf(horaProyeccioon);
      Date da =tm; 
        this.horaProyeccioon = da;
    }
    public void setHoraProyeccioon(Time horaProyeccioon) {
        
      Date da =horaProyeccioon; 
        this.horaProyeccioon = da;
    }

}
